### ISSUE TITLE
Installation of SSH keys doesn't work with multiple users

### ISSUE THREAD

**Issue by leifmadsen** [dadayama/ansible-role-create-user#1]
When you define multiple users in a list, and then provide multiple SSH public keys in the `files/public_keys/<username>.pem` the installation of the public keys does not happen cleanly across all the users.

You'll end up with users without keys installed into the `~/.ssh/authorized_keys` file, and other users setup with the wrong key.

**Comment by yama-sitter** [comment]
> You'll end up with users without keys installed into the ~/.ssh/authorized_keys file, and other users setup with the wrong key.

I fixed.
It was a problem that the value of the public key could not be acquired as an array.
Thank you for your advice.
